kind: ConfigMap
metadata:
  name: {{ include "zeebe-cluster.fullname" . }}
apiVersion: v1
data:
  startup.sh: |
    #!/bin/bash -xeu

    configFile=/usr/local/zeebe/conf/zeebe.cfg.toml
    export ZEEBE_HOST=$(hostname -f)
    export ZEEBE_NODE_ID="${HOSTNAME##*-}"
    
    # We need to specify all brokers as contact points for partition healing to work correctly
    # https://github.com/zeebe-io/zeebe/issues/2684
    ZEEBE_CONTACT_POINTS=${HOSTNAME::-1}0.$(hostname -d):26502
    for (( i=1; i<$ZEEBE_CLUSTER_SIZE; i++ ))
    do
        ZEEBE_CONTACT_POINTS="${ZEEBE_CONTACT_POINTS},${HOSTNAME::-1}$i.$(hostname -d):26502"
    done
    export ZEEBE_CONTACT_POINTS="${ZEEBE_CONTACT_POINTS}"
    
    exec /usr/local/zeebe/bin/broker
  zeebe.cfg.toml: |
    # For more information about this configuration visit: https://docs.zeebe.io/operations/the-zeebecfgtoml-file.html
    [threads]
    cpuThreadCount = "{{ .Values.zeebe.cpu.thread.count | default 2 }}"
    ioThreadCount = "{{ .Values.zeebe.io.thread.count | default 2 }}"
    [[exporters]]
    id = "elasticsearch"
    className = "io.zeebe.exporter.ElasticsearchExporter"
      [exporters.args]
      url = "http://{{ .Values.global.elasticsearch.host }}:{{ .Values.global.elasticsearch.port }}"

      [exporters.args.bulk]
      delay = 5
      size = 1_000

      #[exporters.args.authentication]
      #username = elastic
      #password = changeme

      [exporters.args.index]
      prefix = "zeebe-record"
      createTemplate = true

      command = false
      event = true
      rejection = false

      deployment = true
      incident = true
      job = true
      message = false
      messageSubscription = false
      raft = false
      workflowInstance = true
      workflowInstanceSubscription = false
