apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.global.zeebe | quote }}
  labels:
{{- toYaml  .Values.labels | nindent 4 }}
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.http.port }}
      protocol: TCP
      name: http  
    - port: {{ .Values.service.gateway.port }}
      protocol: TCP
      name: gateway
    - port: {{ .Values.service.command.port }}
      protocol: TCP
      name: command
    - port: {{ .Values.service.internal.port }}
      protocol: TCP
      name: internal  
  selector:
    app.kubernetes.io/name: {{ include "zeebe-cluster.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app: {{ .Values.global.zeebe | quote }}
