apiVersion: v1
kind: Service
metadata:
  name: {{ tpl .Values.global.zeebe . | quote }}
  labels:
    app.kubernetes.io/name: {{ include "zeebe-cluster.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app: {{ tpl .Values.global.zeebe . | quote }}
{{- toYaml  .Values.labels | nindent 4 }}
  annotations:
{{- toYaml  .Values.annotations | nindent 4 }}    
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.http.port }}
      protocol: TCP
      name: {{ .Values.service.http.name | default "http" }}  
    - port: {{ .Values.service.gateway.port }}
      protocol: TCP
      name: {{ .Values.service.gateway.name | default "gateway" }}
  selector:
    app.kubernetes.io/name: {{ include "zeebe-cluster.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app: {{ tpl .Values.global.zeebe . | quote }}
